Added testing
Redactie-Portaal/backend-actor-model pull request #38
Opened 2022-04-21 12:17 UTC by chasit

2022-04-21 12:38 UTC, joepvand requested changes

2022-04-21 12:38 UTC, joepvand commented on RedacteurPortaal.Api/appsettings.json
> +    "DefaultConnection": "Server=127.0.0.1;Port=5433;Database=RedactiePortaal.Data;Username=postgres;Password=MyStrongPassword;"
postgres postgres

2022-04-21 12:38 UTC, joepvand commented on RedacteurPortaal.Grains/Grains/NewsItemGrain.cs
> +        //var grain = this.GrainFactory.GetGrain<INewsItemDescriptionGrain>(this.newsItem.State.Id);
commented out code geeft me kanker

2022-04-21 12:44 UTC, joepvand approved these changes

2022-04-21 13:56 UTC, ahmedjimale1998 approved these changes

2022-04-21 13:56 UTC, ahmedjimale1998 commented on RedacteurPortaal.DomainModels/NewsItem/NewsItemUpdate.cs
> +            this.ProductionDate = produtionDate;
Change field name from produtionDate to productionDate

2022-04-25 07:31 UTC, joepvand requested changes

2022-04-25 07:31 UTC, joepvand commented on RedacteurPortaal.Grains/Grains/ArchiveGrain.cs
> +    [PersistentState("archive")]
orleansstorage

2022-04-25 07:31 UTC, joepvand commented on RedacteurPortaal.Tests/Grains.Test/ArchiveGrainTests.cs
> +        //await archiveGrain
verwijder de commented out code

2022-04-25 07:31 UTC, joepvand commented on RedacteurPortaal.Tests/Grains.Test/AddressGrainTests.cs
> +        //var address = ClusterFixture.GrainStorage.GetGrainState<AddressModel>(addressGrain);
dit kan ook weg

2022-04-25 07:31 UTC, joepvand commented on RedacteurPortaal.Tests/Grains.Test/ContactGrainTests.cs
> +        //var contact = ClusterFixture.GrainStorage.GetGrainState<Contact>(contactGrain);
dit weg

2022-04-25 07:31 UTC, joepvand commented on RedacteurPortaal.Tests/Grains.Test/LocationGrainTests.cs
> +        //var location = ClusterFixture.GrainStorage.GetGrainState<Location>(locationGrain);
weg

2022-04-25 07:31 UTC, joepvand commented on RedacteurPortaal.Tests/Grains.Test/MediaPhotoGrainTests.cs
> +        //var mediaPhotoItem = ClusterFixture.GrainStorage.GetGrainState<MediaPhotoItem>(mediaPhotoGrain);
weg
 overal

2022-04-25 07:31 UTC, joepvand commented on RedacteurPortaal.Tests/Grains.Test/NewsItemDescriptionGrainTests.cs
> +        //var guid = Guid.NewGuid();
mooie test <3

2022-04-25 08:34 UTC, joepvand requested changes

2022-04-25 08:34 UTC, joepvand commented on RedacteurPortaal.Api/Controllers/ProfileController.cs
> +            return this.Ok(updateProfile);
Createdataction

2022-04-25 08:59 UTC, joepvand approved these changes

2022-04-25 09:02 UTC, merged