RDP-129 Address Book Unit test
Redactie-Portaal/backend-actor-model pull request #49
Opened 2022-04-28 11:23 UTC by ahmedjimale1998

2022-04-28 11:28 UTC, joepvand requested changes

2022-04-28 11:28 UTC, joepvand commented on RedacteurPortaal.Api/Controllers/AddressController.cs
> +            return this.Ok("Address updated");
```suggestion
            return grain.Get();
```

2022-04-28 11:28 UTC, joepvand commented on RedacteurPortaal.Api/Models/NewsItemDTO.cs
> +    public Guid? Id { get; set; } = Guid.NewGuid();
```suggestion
    public Guid? Id { get; set; }
```

2022-04-28 11:28 UTC, joepvand commented on RedacteurPortaal.Api/Models/NewsItemDetailDTO.cs
> +    public MediaVideoItem? Video { get; set; }
returnen we geen array aan video items?

2022-04-28 11:28 UTC, joepvand commented on RedacteurPortaal.DomainModels/Address/AddressModel.cs
> +            this.CompanyName= companyName ?? throw new ArgumentNullException(nameof(companyName));
```suggestion
            this.CompanyName = companyName ?? throw new ArgumentNullException(nameof(companyName));
```

2022-04-28 11:28 UTC, joepvand commented on RedacteurPortaal.Tests/Grains.Test/AddressGrainTests.cs
>          Assert.Equal("Company", address.CompanyName);
Hier kun je alle properties asserten, dan test je test een stuk meer

2022-04-28 11:28 UTC, joepvand commented on RedacteurPortaal.Tests/Grains.Test/AddressGrainTests.cs
> +    [Fact] /*NOT WORKING DUE TO IGRAINMANAGEMENTSERVICE*/
Deze comment kan weg denk ik

2022-04-28 13:47 UTC, chasit requested changes

2022-04-28 13:47 UTC, chasit commented on RedacteurPortaal.DomainModels/Validation/Address/AddressValidator.cs
> +        }
Rules voor email en postcode

2022-04-28 13:47 UTC, chasit commented on RedacteurPortaal.Tests/Grains/AddressGrainTests.cs
> +        /*Assert.Equal(Guid.Empty, deletedAddress.Id);  GUID IS NOT REMOVING WITH DE DELETE FUNCTION */
Niet nodig

2022-05-12 08:27 UTC, chasit requested changes

2022-05-12 08:27 UTC, chasit commented on RedacteurPortaal.DomainModels/Validation/Address/AddressValidator.cs
> +        }
een voor telefoon nr? Kijk hiervoor in contact validator

2022-05-12 12:47 UTC, chasit approved these changes
👍

2022-05-16 08:19 UTC, joepvand approved these changes

2022-05-16 08:22 UTC, merged