Added NewsItem sorting
Redactie-Portaal/backend-actor-model pull request #51
Opened 2022-04-28 12:38 UTC by Dmitri-Lisokonov

pls

2022-05-09 08:28 UTC, chasit requested changes

2022-05-09 08:28 UTC, chasit commented on RedacteurPortaal.Api/Controllers/NewsItemController.cs
> +        var response = list.Where(x => x.ProductionDate >= startDate && x.ProductionDate <= endDate).ToList();
Je gaat nu van een queryable naar een lijst van dto's waarna die weer intern naar een queryable gaat voor die where en m dan weer mapped naar een lijst.

Naar queryable en type mag als laatste dat we dat maar 1x doen,

2022-05-09 08:28 UTC, chasit commented on RedacteurPortaal.Api/Controllers/NewsItemController.cs
> +        var response = list.Where(x => x.Author == employeeId).ToList();
Hier het zelfde als bij sort by date

2022-05-09 08:28 UTC, chasit commented on RedacteurPortaal.Api/Controllers/NewsItemController.cs
> +        var response = list.Where(x => x.Status == parseStatus).ToList();
Hier ook het zelfde

2022-05-09 08:28 UTC, chasit commented on RedacteurPortaal.Api/Controllers/NewsItemController.cs
> +
Hier ook

2022-05-09 12:19 UTC, joepvand commented
Intergration tests <3

2022-05-12 09:36 UTC, joepvand commented on RedacteurPortaal.Grains/GrainServices/GrainManagementService.cs
> +
```suggestion
        public bool GrainExists(Guid id) => this.DbContext.GrainReferences.Any(x => x.GrainId == id)
      
```

2022-05-16 09:41 UTC, chasit approved these changes

2022-05-16 09:42 UTC, joepvand approved these changes

2022-05-16 09:43 UTC, merged